# Generated by Django 3.0.8 on 2021-01-03 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CertificationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=400)),
                ('image', models.CharField(max_length=600)),
                ('section', models.CharField(max_length=40)),
                ('link', models.CharField(max_length=400)),
            ],
        ),
    ]
