# Generated by Django 3.0.8 on 2021-01-03 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tech', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='techmodel',
            name='link',
            field=models.CharField(default=None, max_length=400),
        ),
    ]
