# Generated by Django 3.0.8 on 2021-01-10 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tech', '0002_techmodel_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techsectionmodel',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
