# Generated by Django 3.0.8 on 2021-01-14 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Start', '0002_auto_20201231_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startmodel',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='startModel', to=settings.AUTH_USER_MODEL),
        ),
    ]
