# Generated by Django 3.0.8 on 2021-01-02 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Creative', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creativemodel',
            name='link',
            field=models.CharField(default=None, max_length=400),
        ),
    ]
